name: Release

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name : Install Prerequisites
      run : |
        sudo apt-get install gcc libpq-dev -y
        sudo apt-get install python-dev  python-pip -y
        sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
        python -m pip install build --user
        pip3 install wheel
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        skip_existing: true
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: jlurye-ksg
        password: ${{ secrets.pypi_password }}
        skip_existing: true  